// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgelbOwzuVvwBE2HW7W3K1rQPmXi-rrjg',
    appId: '1:552605403111:web:a7d816f1b8a5d9b9f99f42',
    messagingSenderId: '552605403111',
    projectId: 'infocar-16375',
    authDomain: 'infocar-16375.firebaseapp.com',
    databaseURL: 'https://infocar-16375-default-rtdb.firebaseio.com',
    storageBucket: 'infocar-16375.appspot.com',
    measurementId: 'G-SVSZS1J81W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjizr-IIZO2FZ5J0D28lP6NxAEsiXhvUw',
    appId: '1:552605403111:android:c45c33f0d1e35168f99f42',
    messagingSenderId: '552605403111',
    projectId: 'infocar-16375',
    databaseURL: 'https://infocar-16375-default-rtdb.firebaseio.com',
    storageBucket: 'infocar-16375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9qIeGTVFkHGUO3owb3-Om7HNVwuuyN8',
    appId: '1:552605403111:ios:d658077a5f7e8859f99f42',
    messagingSenderId: '552605403111',
    projectId: 'infocar-16375',
    databaseURL: 'https://infocar-16375-default-rtdb.firebaseio.com',
    storageBucket: 'infocar-16375.appspot.com',
    iosBundleId: 'com.example.imagestorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU9qIeGTVFkHGUO3owb3-Om7HNVwuuyN8',
    appId: '1:552605403111:ios:d658077a5f7e8859f99f42',
    messagingSenderId: '552605403111',
    projectId: 'infocar-16375',
    databaseURL: 'https://infocar-16375-default-rtdb.firebaseio.com',
    storageBucket: 'infocar-16375.appspot.com',
    iosBundleId: 'com.example.imagestorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgelbOwzuVvwBE2HW7W3K1rQPmXi-rrjg',
    appId: '1:552605403111:web:0bf9d6eebda56936f99f42',
    messagingSenderId: '552605403111',
    projectId: 'infocar-16375',
    authDomain: 'infocar-16375.firebaseapp.com',
    databaseURL: 'https://infocar-16375-default-rtdb.firebaseio.com',
    storageBucket: 'infocar-16375.appspot.com',
    measurementId: 'G-9Z9SM3PPQR',
  );
}
